version: '3.9'

services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python
    volumes:
      - ./:/app
    command: tail -f /dev/null
    ports:
      - "5678:5678"
    working_dir: /app
